version: '3.5'

services:
  trending-command-service:
    image: trending-command-service:dev
    build:
      context: .
      dockerfile: Trending.Command.Api/Dockerfile
      args:
        - SDK_VERSION=3.1.301
    environment:
      - MONGODB=mongodb://mongodb:27017
    ports:
      - "32780:80"

networks:
  default:
    external: true
    name: shared-infrastructure-network