version: "3.5"

services:
  mongodb:
    image: mongo
    networks:
      -  shared-infrastructure-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
       
networks:
   shared-infrastructure-network:
     name: shared-infrastructure-network

volumes:
  mongo-data: